-- ============================================================
-- App 2 Tier 3: stackedge -> stackworks, live database objects
-- ============================================================
--
-- Part of the same user-directed full internal rename as
-- 103/104_flexpro_rename*.sql. This app carries an extra wrinkle App 1
-- didn't have: stackedge was ITSELF a rename from an even older
-- codename, "Prolab" (047_rename_prolab_to_stackedge.sql), and that
-- earlier rename left an orphaned identifier behind -- the CHECK
-- constraint governing profiles.stackedge_role is still literally
-- named `profiles_prolab_role_check` (auto-generated by Postgres from
-- the original `prolab_role` column name in 030_prolab_launch.sql;
-- 047's own comment claimed "no separate constraint rename needed",
-- which is only half true -- RENAME COLUMN does carry the constraint's
-- internal column reference automatically, but not the constraint's
-- own name). Fixed properly here rather than carried forward again.
--
-- Same discipline as 103: every literal-string-value object below was
-- catalogued by reading every one of the 104 existing migration files
-- for its LATEST authoritative definition, then cross-checked against
-- the live database directly (pg_constraint for the exact live
-- profiles_prolab_role_check definition, pg_depend for greyin_scores'
-- dependents, actual row counts) before writing this file.
--
-- Live row counts confirmed immediately before writing this migration
-- (2026-09-03): pillar_memberships.pillar='stackedge' (183),
-- profiles.stackedge_role='builder' (183, 0 'supporter'),
-- llm_feature_flags.feature_key='stackedge_verification' (1).
--
-- greyin_scores' live dependents reconfirmed unchanged from 103's own
-- research: exactly platform_people_index (view) + 4 RLS policies on
-- posts/comments, none of which read the stackedge_* columns
-- specifically -- their recreated bodies below are reused verbatim
-- from 103.
--
-- One RLS policy needs NO action here despite referencing
-- stackedge_role: "Project owners who are Builders can create asks" on
-- project_asks (030_prolab_launch.sql:85-94) was written against
-- `prolab_role` and never updated after 047's column rename -- but RLS
-- policy quals are stored as parsed expression trees bound by attnum,
-- not text, so it already transparently reads `stackedge_role` today
-- and will transparently follow this migration's rename to
-- `stackworks_role` too, the same way client_jobs/gigs' policies
-- transparently followed 103's freeagent_subscriptions table rename.
--
-- Also NOT touched here (pre-existing, unrelated, flagged not fixed):
-- the `collaborators` view is still missing security_invoker=true
-- (067 set it, 089's CREATE OR REPLACE silently dropped it) -- same
-- finding 103 already recorded, still true, still out of scope for a
-- naming migration.
--
-- Run this after 104_flexpro_subscriptions_constraint_names.sql
-- ============================================================

BEGIN;

-- ------------------------------------------------------------
-- 1. profiles.stackedge_role -> stackworks_role, and its orphaned
-- constraint name fixed properly this time.
-- ------------------------------------------------------------
ALTER TABLE public.profiles RENAME COLUMN stackedge_role TO stackworks_role;
ALTER TABLE public.profiles RENAME CONSTRAINT profiles_prolab_role_check TO profiles_stackworks_role_check;

-- ------------------------------------------------------------
-- 2. handle_email_confirmed() -- fires on every signup, any pillar.
-- 103's exact current body, reproduced byte-for-byte except the
-- stackedge_role variable/column/metadata-key references and the
-- 'stackedge' pillar literal this migration exists to change. The
-- metadata key (meta->>'stackworks_role') must match what
-- apps/stackworks/src/app/auth/signup/route.ts sends -- that app-code
-- change ships in the same deploy as this migration, not before.
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.handle_email_confirmed()
RETURNS TRIGGER AS $$
DECLARE
  meta JSONB := NEW.raw_user_meta_data;
  user_role TEXT := COALESCE(meta->>'role', 'candidate');
  full_name TEXT := trim(concat(meta->>'first_name', ' ', meta->>'last_name'));
  v_pillar TEXT;
  v_stackworks_role TEXT := meta->>'stackworks_role';
  v_years_experience INTEGER := NULLIF(meta->>'years_experience', '')::INTEGER;
BEGIN
  IF NEW.email_confirmed_at IS NULL OR OLD.email_confirmed_at IS NOT NULL THEN
    RETURN NEW;
  END IF;

  IF user_role = 'admin' THEN
    user_role := 'candidate';
  END IF;

  INSERT INTO public.profiles (id, email, full_name, role, years_experience, stackworks_role)
  VALUES (
    NEW.id, NEW.email, NULLIF(full_name, ''), user_role,
    v_years_experience, v_stackworks_role
  )
  ON CONFLICT (id) DO UPDATE SET
    email = EXCLUDED.email,
    full_name = COALESCE(EXCLUDED.full_name, public.profiles.full_name),
    role = EXCLUDED.role,
    years_experience = COALESCE(EXCLUDED.years_experience, public.profiles.years_experience),
    stackworks_role = COALESCE(EXCLUDED.stackworks_role, public.profiles.stackworks_role),
    updated_at = NOW();

  IF user_role = 'employer' THEN
    INSERT INTO public.companies (user_id, name, slug)
    VALUES (NEW.id, COALESCE(NULLIF(full_name, ''), NEW.email) || '''s Company', 'company-' || substr(NEW.id::text, 1, 8))
    ON CONFLICT (user_id) DO NOTHING;
  ELSIF user_role = 'candidate' THEN
    INSERT INTO public.candidates (user_id, experience_years)
    VALUES (NEW.id, v_years_experience)
    ON CONFLICT (user_id) DO NOTHING;
  END IF;

  v_pillar := CASE
    WHEN user_role IN ('candidate', 'employer') THEN 'greyin'
    WHEN user_role IN ('client', 'freelancer') THEN 'flexpro'
    WHEN user_role = 'member' THEN 'saltnpepper'
    WHEN user_role IN ('author', 'follower') THEN 'greymatters'
  END;
  IF v_pillar IS NOT NULL THEN
    INSERT INTO public.pillar_memberships (user_id, pillar, role)
    VALUES (NEW.id, v_pillar, user_role)
    ON CONFLICT (user_id, pillar) DO NOTHING;
  END IF;

  IF v_stackworks_role IS NOT NULL THEN
    INSERT INTO public.pillar_memberships (user_id, pillar, role)
    VALUES (NEW.id, 'stackworks', v_stackworks_role)
    ON CONFLICT (user_id, pillar) DO NOTHING;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- ------------------------------------------------------------
-- 3. greyin_scores -- stackedge_score/stackedge_evidence/
-- stackedge_headcount are real output columns, same situation as
-- freeagent_score in 103: CREATE OR REPLACE VIEW can't rename them in
-- place, so DROP ... CASCADE + recreate, same verified-safe dependents
-- (platform_people_index + 4 RLS policies on posts/comments, none of
-- which read the stackedge_*/stackworks_* columns).
-- ------------------------------------------------------------
DROP VIEW public.greyin_scores CASCADE;

CREATE VIEW public.greyin_scores AS
WITH constants AS (
  SELECT 3 AS m_stackworks, 5 AS m_flexpro, 10 AS m_saltnpepper, 5 AS m_greymatters, 3 AS m_peer
),
stackworks_raw AS (
  SELECT subject_user_id AS user_id, AVG(score)::numeric AS raw, COUNT(*) AS v
  FROM public.verified_outcomes
  WHERE status = 'verified'
  GROUP BY subject_user_id
),
flexpro_raw AS (
  SELECT id AS user_id, (seller_rating / 5.0 * 100)::numeric AS raw, total_reviews AS v
  FROM public.profiles
  WHERE total_reviews > 0
),
saltnpepper_raw AS (
  SELECT user_id, (LEAST(SUM(points), 100)::numeric / 100 * 100) AS raw, COUNT(*) AS v
  FROM public.reputation_events
  WHERE event_type = 'project_upvoted'
  GROUP BY user_id
),
greymatters_raw AS (
  SELECT subject_user_id AS user_id, AVG(score)::numeric AS raw, COUNT(*) AS v
  FROM public.ai_quality_scores
  WHERE content_type = 'greymatters_post'
  GROUP BY subject_user_id
),
peer_raw AS (
  SELECT ratee_id AS user_id, (AVG(contribution_rating) / 5.0 * 100)::numeric AS raw, COUNT(*) AS v
  FROM public.peer_project_ratings
  GROUP BY ratee_id
),
platform_stats AS (
  SELECT
    (SELECT AVG(raw) FROM stackworks_raw) AS stackworks_mean,
    (SELECT COUNT(*) FROM stackworks_raw) AS stackworks_headcount,
    (SELECT AVG(raw) FROM flexpro_raw) AS flexpro_mean,
    (SELECT COUNT(*) FROM flexpro_raw) AS flexpro_headcount,
    (SELECT AVG(raw) FROM saltnpepper_raw) AS saltnpepper_mean,
    (SELECT COUNT(*) FROM saltnpepper_raw) AS saltnpepper_headcount,
    (SELECT AVG(raw) FROM greymatters_raw) AS greymatters_mean,
    (SELECT COUNT(*) FROM greymatters_raw) AS greymatters_headcount,
    (SELECT AVG(raw) FROM peer_raw) AS peer_mean,
    (SELECT COUNT(*) FROM peer_raw) AS peer_headcount
),
per_user AS (
  SELECT
    p.id AS user_id,
    p.years_experience,
    pr.v AS stackworks_evidence,
    pr.raw AS stackworks_raw,
    CASE WHEN pr.v IS NOT NULL THEN
      ROUND((pr.v::numeric / (pr.v + c.m_stackworks)) * pr.raw + (c.m_stackworks::numeric / (pr.v + c.m_stackworks)) * s.stackworks_mean)
    END AS stackworks_score,
    fa.v AS flexpro_evidence,
    fa.raw AS flexpro_raw,
    CASE WHEN fa.v IS NOT NULL THEN
      ROUND((fa.v::numeric / (fa.v + c.m_flexpro)) * fa.raw + (c.m_flexpro::numeric / (fa.v + c.m_flexpro)) * s.flexpro_mean)
    END AS flexpro_score,
    sp.v AS saltnpepper_evidence,
    sp.raw AS saltnpepper_raw,
    CASE WHEN sp.v IS NOT NULL THEN
      ROUND((sp.v::numeric / (sp.v + c.m_saltnpepper)) * sp.raw + (c.m_saltnpepper::numeric / (sp.v + c.m_saltnpepper)) * s.saltnpepper_mean)
    END AS saltnpepper_score,
    gm.v AS greymatters_evidence,
    gm.raw AS greymatters_raw,
    CASE WHEN gm.v IS NOT NULL THEN
      ROUND((gm.v::numeric / (gm.v + c.m_greymatters)) * gm.raw + (c.m_greymatters::numeric / (gm.v + c.m_greymatters)) * s.greymatters_mean)
    END AS greymatters_score,
    pe.v AS peer_evidence,
    pe.raw AS peer_raw,
    CASE WHEN pe.v IS NOT NULL THEN
      ROUND((pe.v::numeric / (pe.v + c.m_peer)) * pe.raw + (c.m_peer::numeric / (pe.v + c.m_peer)) * s.peer_mean)
    END AS peer_score,
    s.stackworks_headcount, s.flexpro_headcount, s.saltnpepper_headcount, s.greymatters_headcount, s.peer_headcount
  FROM public.profiles p
  CROSS JOIN constants c
  CROSS JOIN platform_stats s
  LEFT JOIN stackworks_raw pr ON pr.user_id = p.id
  LEFT JOIN flexpro_raw fa ON fa.user_id = p.id
  LEFT JOIN saltnpepper_raw sp ON sp.user_id = p.id
  LEFT JOIN greymatters_raw gm ON gm.user_id = p.id
  LEFT JOIN peer_raw pe ON pe.user_id = p.id
),
scored AS (
  SELECT
    user_id,
    stackworks_score, stackworks_evidence, stackworks_headcount,
    flexpro_score, flexpro_evidence, flexpro_headcount,
    saltnpepper_score, saltnpepper_evidence, saltnpepper_headcount,
    greymatters_score, greymatters_evidence, greymatters_headcount,
    years_experience,
    ROUND(
      (
        COALESCE(stackworks_score * LN(stackworks_headcount + 1), 0) +
        COALESCE(flexpro_score * LN(flexpro_headcount + 1), 0) +
        COALESCE(saltnpepper_score * LN(saltnpepper_headcount + 1), 0) +
        COALESCE(greymatters_score * LN(greymatters_headcount + 1), 0)
      ) / NULLIF(
        (CASE WHEN stackworks_score IS NOT NULL THEN LN(stackworks_headcount + 1) ELSE 0 END) +
        (CASE WHEN flexpro_score IS NOT NULL THEN LN(flexpro_headcount + 1) ELSE 0 END) +
        (CASE WHEN saltnpepper_score IS NOT NULL THEN LN(saltnpepper_headcount + 1) ELSE 0 END) +
        (CASE WHEN greymatters_score IS NOT NULL THEN LN(greymatters_headcount + 1) ELSE 0 END),
        0
      )
    ) AS platform_composite,
    CASE WHEN stackworks_score IS NOT NULL OR flexpro_score IS NOT NULL OR saltnpepper_score IS NOT NULL OR greymatters_score IS NOT NULL THEN
      ROUND(
        0.85 * (
          (
            COALESCE(stackworks_score * LN(stackworks_headcount + 1), 0) +
            COALESCE(flexpro_score * LN(flexpro_headcount + 1), 0) +
            COALESCE(saltnpepper_score * LN(saltnpepper_headcount + 1), 0) +
            COALESCE(greymatters_score * LN(greymatters_headcount + 1), 0)
          ) / NULLIF(
            (CASE WHEN stackworks_score IS NOT NULL THEN LN(stackworks_headcount + 1) ELSE 0 END) +
            (CASE WHEN flexpro_score IS NOT NULL THEN LN(flexpro_headcount + 1) ELSE 0 END) +
            (CASE WHEN saltnpepper_score IS NOT NULL THEN LN(saltnpepper_headcount + 1) ELSE 0 END) +
            (CASE WHEN greymatters_score IS NOT NULL THEN LN(greymatters_headcount + 1) ELSE 0 END),
            0
          )
        ) + 0.15 * (LEAST(COALESCE(years_experience, 0), 20) / 20.0 * 100)
      )
    END AS greyin_score
  FROM per_user
),
gated AS (
  SELECT
    *,
    (
      COALESCE(years_experience, 0) >= (SELECT min_years_experience FROM public.platform_gate_settings WHERE id = 1)
      OR COALESCE(greyin_score, 0) >= (SELECT min_greyin_score FROM public.platform_gate_settings WHERE id = 1)
    ) AS is_verified_expert
  FROM scored
)
SELECT gated.*, pu.peer_score, pu.peer_evidence, pu.peer_headcount
FROM gated
JOIN per_user pu ON pu.user_id = gated.user_id;

GRANT SELECT ON public.greyin_scores TO anon, authenticated;

-- 103's exact body, unchanged -- dropped by the CASCADE above purely
-- as a side effect of depending on greyin_scores' column list.
CREATE OR REPLACE VIEW public.platform_people_index AS
SELECT
  p.id AS user_id,
  p.full_name,
  p.location,
  gs.greyin_score,
  COALESCE(gs.is_verified_expert, false) AS is_verified_expert,
  COALESCE(vo.verified_outcomes_count, 0) AS verified_outcomes_count,
  COALESCE(ps.skills, ARRAY[]::text[]) AS skills,
  c.availability,
  c.current_title,
  p.is_mentor,
  p.mentor_domain
FROM public.profiles p
LEFT JOIN public.greyin_scores gs ON gs.user_id = p.id
LEFT JOIN public.candidates c ON c.user_id = p.id
LEFT JOIN (
  SELECT subject_user_id, COUNT(*) AS verified_outcomes_count
  FROM public.verified_outcomes
  WHERE status = 'verified'
  GROUP BY subject_user_id
) vo ON vo.subject_user_id = p.id
LEFT JOIN (
  SELECT user_id, array_agg(skill ORDER BY skill) AS skills
  FROM public.profile_skills
  GROUP BY user_id
) ps ON ps.user_id = p.id;

-- Same 4 policies 103 had to recreate, unchanged -- dropped again by
-- this DROP ... CASCADE for the same reason.
CREATE POLICY "Published posts respect their view audience"
  ON public.posts FOR SELECT
  USING (
    status = 'published' AND (
      view_audience = 'public'
      OR (view_audience = 'follower' AND auth.role() = 'authenticated')
      OR (view_audience = 'verified_expert' AND EXISTS (SELECT 1 FROM public.greyin_scores WHERE greyin_scores.user_id = auth.uid() AND greyin_scores.is_verified_expert))
    )
  );

CREATE POLICY "Verified experts can insert posts"
  ON public.posts FOR INSERT
  WITH CHECK (
    auth.uid() = author_id AND (
      EXISTS (SELECT 1 FROM public.greyin_scores WHERE greyin_scores.user_id = auth.uid() AND greyin_scores.is_verified_expert)
      OR EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
    )
  );

CREATE POLICY "Approved comments respect their post's comment audience"
  ON public.comments FOR SELECT
  USING (
    status = 'approved' AND EXISTS (
      SELECT 1 FROM public.posts p WHERE p.id = comments.post_id AND (
        p.comment_audience = 'public'
        OR (p.comment_audience = 'follower' AND auth.role() = 'authenticated')
        OR (p.comment_audience = 'verified_expert' AND EXISTS (SELECT 1 FROM public.greyin_scores WHERE greyin_scores.user_id = auth.uid() AND greyin_scores.is_verified_expert))
      )
    )
  );

CREATE POLICY "Comments respect their post's comment audience"
  ON public.comments FOR INSERT
  WITH CHECK (
    auth.uid() = user_id AND EXISTS (
      SELECT 1 FROM public.posts p WHERE p.id = comments.post_id AND (
        p.comment_audience = 'public'
        OR (p.comment_audience = 'follower' AND auth.role() = 'authenticated')
        OR (p.comment_audience = 'verified_expert' AND EXISTS (SELECT 1 FROM public.greyin_scores WHERE greyin_scores.user_id = auth.uid() AND greyin_scores.is_verified_expert))
      )
    )
  );

-- ------------------------------------------------------------
-- 4. The other 4 UNION ALL views -- literal pillar-tag VALUES only.
-- platform_search_index and activity_feed carry security_invoker=true
-- live -- reissued after CREATE OR REPLACE resets it, same as 103.
-- collaborators deliberately NOT reissued (see header note).
-- ------------------------------------------------------------
CREATE OR REPLACE VIEW public.platform_search_index AS
  SELECT 'post'::text AS type,
    'greymatters'::text AS pillar,
    posts.id, posts.title, posts.excerpt AS description,
    '/posts/'::text || posts.slug AS path, posts.created_at
  FROM posts WHERE posts.status = 'published'::text
UNION ALL
  SELECT 'job'::text AS type,
    'greyin'::text AS pillar,
    jobs.id, jobs.title, jobs.description,
    '/jobs/'::text || jobs.id AS path, jobs.created_at
  FROM jobs WHERE jobs.status = 'open'::text
UNION ALL
  SELECT 'gig'::text AS type,
    'flexpro'::text AS pillar,
    gigs.id, gigs.title, gigs.description,
    '/gigs/'::text || gigs.id AS path, gigs.created_at
  FROM gigs WHERE gigs.status = 'active'::text
UNION ALL
  SELECT 'discussion'::text AS type,
    'saltnpepper'::text AS pillar,
    discussions.id, discussions.title, discussions.body AS description,
    '/discussions/'::text || discussions.id AS path, discussions.created_at
  FROM discussions
UNION ALL
  SELECT 'project'::text AS type,
    'stackworks'::text AS pillar,
    builder_projects.id, builder_projects.title, builder_projects.description,
    '/projects/'::text || builder_projects.id AS path, builder_projects.created_at
  FROM builder_projects;

ALTER VIEW public.platform_search_index SET (security_invoker = true);

-- 103's exact body -- 'expertedge' pillar tags here are DeepEdge's
-- divergence (App 3's own pass), deliberately untouched.
CREATE OR REPLACE VIEW public.my_pillar_activity AS
SELECT * FROM (
  SELECT subject_user_id AS user_id, 'stackworks' AS pillar, 'verified_outcome' AS event_type, created_at AS occurred_at FROM public.verified_outcomes
  UNION ALL
  SELECT user_id, 'stackworks', 'project_created', created_at FROM public.builder_projects
  UNION ALL
  SELECT created_by, 'stackworks', 'ask_created', created_at FROM public.project_asks
  UNION ALL
  SELECT reviewee_id, 'flexpro', 'review_received', created_at FROM public.order_reviews
  UNION ALL
  SELECT freelancer_id, 'flexpro', 'gig_listed', created_at FROM public.gigs
  UNION ALL
  SELECT author_id, 'saltnpepper', 'discussion', created_at FROM public.discussions
  UNION ALL
  SELECT author_id, 'saltnpepper', 'discussion_reply', created_at FROM public.discussion_replies
  UNION ALL
  SELECT author_id, 'greymatters', 'post', created_at FROM public.posts WHERE author_id IS NOT NULL
  UNION ALL
  SELECT user_id, 'greymatters', 'comment', created_at FROM public.comments
  UNION ALL
  SELECT c.user_id, 'expertedge', 'application', a.applied_at FROM public.applications a JOIN public.candidates c ON c.id = a.candidate_id
  UNION ALL
  SELECT co.user_id, 'expertedge', 'job_posted', j.created_at FROM public.jobs j JOIN public.companies co ON co.id = j.company_id
) t
WHERE user_id = auth.uid();

GRANT SELECT ON public.my_pillar_activity TO authenticated;

CREATE OR REPLACE VIEW public.activity_feed AS
  SELECT
    'greymatters'::text AS pillar,
    'post'::text AS content_type,
    posts.id,
    posts.author_id,
    posts.title,
    posts.excerpt AS description,
    COALESCE(posts.published_at, posts.created_at) AS occurred_at,
    '/posts/' || posts.slug AS path,
    posts.feed_visibility
  FROM public.posts
  WHERE posts.status = 'published'
UNION ALL
  SELECT
    'saltnpepper'::text,
    'discussion'::text,
    discussions.id,
    CASE WHEN discussions.is_anonymous THEN NULL ELSE discussions.author_id END,
    discussions.title,
    discussions.body AS description,
    discussions.created_at AS occurred_at,
    '/discussions/' || discussions.id AS path,
    discussions.feed_visibility
  FROM public.discussions
UNION ALL
  SELECT
    'stackworks'::text,
    'project_update'::text,
    pu.id,
    pu.author_id,
    'Update on ' || bp.title AS title,
    pu.body AS description,
    pu.created_at AS occurred_at,
    '/projects/' || pu.project_id AS path,
    pu.feed_visibility
  FROM public.project_updates pu
  JOIN public.builder_projects bp ON bp.id = pu.project_id
UNION ALL
  SELECT
    'flexpro'::text,
    'gig'::text,
    gigs.id,
    gigs.freelancer_id,
    gigs.title,
    gigs.description,
    gigs.created_at AS occurred_at,
    '/gigs/' || gigs.id AS path,
    gigs.feed_visibility
  FROM public.gigs
  WHERE gigs.status = 'active'
UNION ALL
  SELECT
    'greyin'::text,
    'job'::text,
    j.id,
    co.user_id,
    j.title,
    j.description,
    j.created_at AS occurred_at,
    '/jobs/' || j.id AS path,
    j.feed_visibility
  FROM public.jobs j
  JOIN public.companies co ON co.id = j.company_id
  WHERE j.status = 'open';

ALTER VIEW public.activity_feed SET (security_invoker = true);

CREATE OR REPLACE VIEW public.collaborators AS
  SELECT ask.created_by AS user_id, pa.applicant_id AS collaborator_id, 'stackworks'::text AS pillar, pa.created_at AS occurred_at
  FROM public.project_applications pa
  JOIN public.project_asks ask ON ask.id = pa.ask_id
  WHERE pa.status = 'accepted'
UNION ALL
  SELECT pa.applicant_id, ask.created_by, 'stackworks'::text, pa.created_at
  FROM public.project_applications pa
  JOIN public.project_asks ask ON ask.id = pa.ask_id
  WHERE pa.status = 'accepted'
UNION ALL
  SELECT go.buyer_id, go.seller_id, 'flexpro'::text, go.completed_at
  FROM public.gig_orders go
  WHERE go.status = 'completed'
UNION ALL
  SELECT go.seller_id, go.buyer_id, 'flexpro'::text, go.completed_at
  FROM public.gig_orders go
  WHERE go.status = 'completed'
UNION ALL
  SELECT m1.user_id, m2.user_id, 'peer'::text, GREATEST(m1.responded_at, m2.responded_at)
  FROM public.peer_project_members m1
  JOIN public.peer_project_members m2 ON m1.project_id = m2.project_id AND m1.user_id <> m2.user_id
  WHERE m1.status = 'confirmed' AND m2.status = 'confirmed';

GRANT SELECT ON public.collaborators TO authenticated;

-- ------------------------------------------------------------
-- 5. pillar_memberships CHECK constraint + its data -- drop, update,
-- re-add, same non-negotiable order 103 established (adding the
-- stricter constraint before updating the data it would reject fails
-- immediately against the still-old-valued rows).
-- ------------------------------------------------------------
ALTER TABLE public.pillar_memberships DROP CONSTRAINT pillar_memberships_pillar_check;
UPDATE public.pillar_memberships SET pillar = 'stackworks' WHERE pillar = 'stackedge';
ALTER TABLE public.pillar_memberships ADD CONSTRAINT pillar_memberships_pillar_check
  CHECK (pillar = ANY (ARRAY['greyin', 'greymatters', 'saltnpepper', 'flexpro', 'stackworks', 'longlist']));

-- Rename+recreate rather than a plain ALTER POLICY RENAME -- the name
-- isn't the only thing that needs to change, its own literal
-- 'stackedge' condition does too, and RENAME alone can't touch that.
DROP POLICY "Anyone authenticated can view stackedge pillar memberships" ON public.pillar_memberships;
CREATE POLICY "Anyone authenticated can view stackworks pillar memberships"
  ON public.pillar_memberships FOR SELECT
  USING (auth.role() = 'authenticated' AND pillar = 'stackworks');

-- ------------------------------------------------------------
-- 6. llm_feature_flags -- 1 row (confirmed live immediately before
-- writing this migration).
-- ------------------------------------------------------------
UPDATE public.llm_feature_flags SET feature_key = 'stackworks_verification' WHERE feature_key = 'stackedge_verification';

COMMIT;

NOTIFY pgrst, 'reload schema';
